## define halloween shows here.

phased_hw_trio_red:
  weight: 50
  duration: 300
  groups:
    eves:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(hw_trio), black, black ]
    trees:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ red, black, black ]
            sx: 166
            ix: 153

colorful_hw_dual_all:
  weight: 50
  duration: 300
  groups:
    all:
      preset: colorful
      data:
        transition: 75
        seg:
          - col: [ $rand_list<c1>(!hw_trio), $rand_list<c2>(!hw_trio), black ]

colorful_hw_dual_split:
  weight: 50
  duration: 300
  groups:
    eves:
      preset: colorful
      data:
        transition: 75
        seg:
          - col: [ $rand_list<c1>(!hw_trio), $rand_list<c2>(!hw_trio), black ]
    trees:
      preset: colorful
      data:
        transition: 75
        seg:
          - col: [ $rand_list<c1>(hw_trio), $rand_list<c3>(!hw_trio), black ]

colorful_hw_trio_all:
  weight: 50
  duration: 300
  groups:
    all:
      preset: colorful
      data:
        transition: 75
        seg:
          - col: [ $rand_list<c1>(!hw_trio), $rand_list<c2>(!hw_trio), $rand_list<c3>(!hw_trio) ]

solid_hw_all:
  weight: 30
  duration: 300
  groups:
    all:
      preset: solid
      data:
        seg:
          - col: [ $rand_list(hw_trio), black, black ]

solid_hw_split:
  weight: 50
  duration: 300
  groups:
    eves:
      preset: solid
      data:
        seg:
          - col: [ $rand_list<eves>(!hw_trio), black, black ]
    trees:
      preset: solid
      data:
        seg:
          - col: [ $rand_list<trees>(!hw_trio), black, black ]