## define halloween shows here.

phased_hw_trio_sngl_red:
  weight: 50
  duration: 300
  groups:
    eves:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(hw_trio), black, black ]
    trees:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ red, black, black ]
            sx: 166
            ix: 153
  floods:
    all:
      chance: 25
      data:
        bri: 10
        col: red

phased_hw_trio_sngl_tri:
  weight: 30
  duration: 300
  groups:
    eves:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(!hw_trio)<c1>, black, black ]
    trees:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(!hw_trio)<c2>, black, black ]
            sx: 166
            ix: 153
  floods:
    all:
      chance: 25
      data:
        bri: 10
        col: $rand_list(!hw_trio)<c3>

phased_hw_trio_sngl_tri_match:
  weight: 30
  duration: 300
  groups:
    eves:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(!hw_trio)<c1>, black, black ]
    trees:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(!hw_trio)<c2>, black, black ]
            sx: 166
            ix: 153
  floods:
    all:
      chance: 25
      data:
        bri: 10
        col: $rand_list(!hw_trio)<c2>

phased_hw_trio_dual_red:
  weight: 30
  duration: 300
  groups:
    eves:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(!hw_trio)<c1>, $rand_list(!hw_trio)<c2>, black ]
            sx: 150
            ix: 25
    trees:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ red, black, black ]
            sx: 150
            ix: 150
  floods:
    all:
      chance: 33
      data:
        bri: 10
        col: $rand_list(!hw_trio)<c3>

phased_hw_trio_dual_match_comp:
  weight: 30
  duration: 300
  groups:
    eves:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(!hw_trio)<c1>, $rand_list(!hw_trio)<c2>, black ]
            sx: 150
            ix: 25
    trees:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(hw_trio)<c1>, $rand_list(hw_trio)<c2>, black ]
            sx: 150
            ix: 25
  floods:
    all:
      chance: 40
      data:
        bri: 10
        col: $rand_list(!hw_trio)<c3>

phased_hw_trio_dual_comp:
  weight: 30
  duration: 300
  groups:
    eves:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(!hw_trio)<c1>, $rand_list(!hw_trio)<c2>, black ]
            sx: 150
            ix: 25
    trees:
      preset: hw_phase
      data:
        transition: 75
        seg:
          - col: [ $rand_list(hw_trio)<c1>, $rand_list(!hw_trio)<c3>, black ]
            sx: 150
            ix: 25
  floods:
    all:
      chance: 33
      data:
        bri: 10
        col: $rand_list(hw_trio)<c3>

colorful_hw_dual_all:
  weight: 50
  duration: 300
  groups:
    all:
      preset: colorful
      data:
        transition: 75
        seg:
          - col: [ $rand_list<c1>(!hw_trio), $rand_list<c2>(!hw_trio), black ]
            grp: 5
  floods:
    all:
      chance: 10
      data:
        bri: 30
        col: $rand_list(!hw_trio)

colorful_hw_dual_split:
  weight: 50
  duration: 300
  groups:
    eves:
      preset: colorful
      data:
        transition: 75
        seg:
          - col: [ $rand_list<c1>(!hw_trio), $rand_list<c2>(!hw_trio), black ]
            grp: 5
    trees:
      preset: colorful
      data:
        transition: 75
        seg:
          - col: [ $rand_list<c1>(hw_trio), $rand_list<c3>(!hw_trio), black ]
            grp: 2
  floods:
    all:
      chance: 10
      data:
        bri: 30
        col: $rand_list<c3>(hw_trio)


colorful_hw_trio_all:
  weight: 50
  duration: 300
  groups:
    all:
      preset: colorful
      data:
        transition: 75
        bri: 200
        seg:
          - col: [ $rand_list<c1>(!hw_trio), $rand_list<c2>(!hw_trio), $rand_list<c3>(!hw_trio) ]
            grp: 5
  floods:
    all:
      chance: 10
      data:
        bri: 30
        col: red

solid_hw_all:
  weight: 30
  duration: 300
  groups:
    all:
      preset: solid
      data:
        seg:
          - col: [ $rand_list(!hw_trio), black, black ]
  floods:
    all:
      chance: 90
      data:
        col: $rand_list(!hw_trio)
        bri: 40

solid_hw_split_trio:
  weight: 50
  duration: 300
  groups:
    eves:
      preset: solid
      data:
        seg:
          - col: [ $rand_list(!hw_trio)<c1>, black, black ]
    trees:
      preset: solid
      data:
        seg:
          - col: [ $rand_list(!hw_trio)<c2>, black, black ]
  floods:
    all:
      chance: 90
      data:
        col: $rand_list(!hw_trio)<c3>
        bri: 33

solid_hw_split_dual:
  weight: 50
  duration: 300
  groups:
    eves:
      preset: solid
      data:
        seg:
          - col: [ $rand_list(!hw_trio)<c1>, black, black ]
    trees:
      preset: solid
      data:
        seg:
          - col: [ $rand_list(!hw_trio)<c2>, black, black ]
  floods:
    all:
      chance: 90
      data:
        col: $rand_list(!hw_trio)<c2>
        bri: 33