red:          [255, 0, 0]
green:        [0, 255, 0]
blue:         [0, 0, 255]
yellow:       [255, 255, 0]
cyan:         [0, 255,255]
magenta:      [ 255,0,255]
purple:       [ 200,0, 255]
hw_purple:    [153,0,255]
hw_green:     [0, 255, 150]
white:        [255, 255, 255]
warm_white:   [255, 245, 200]
cool_white:   [240,240,255]
dim_white:    [100,100,90]
uv:           [80, 0, 255]
ghost_green:  [0, 255, 80]
orange:       [255, 196, 0]
black:        [0, 0, 0]
red_dim:      [135,0,0]
green_dim:    [0,135,0]
blue_dim:     [0,0,135]
white_dim:    [120,120,120]
white_med:    [190,190,190]