rgb-1: 
  disabled: False
  topic: 'floods/light/rgb-1/command'
  
rgb-2: 
  disabled: False
  topic: 'floods/light/rgb-2/command'

rgb-3: 
  disabled: False
  topic: 'floods/light/rgb-3/command'

rgb-4: 
  disabled: False
  topic: 'floods/light/rgb-4/command'