# porch 1
rgb-1: 
  disabled: False
  topic: 'floods/light/rgb-1/command'
  scalars:
    brightness: 225
    hue: -7
    r: 245
  
# porch 2
rgb-2: 
  disabled: False
  topic: 'floods/light/rgb-2/command'
  scalars:
    brightness: 225
    hue: -7
    r: 245

# skeleton
rgb-3: 
  disabled: False
  topic: 'floods/light/rgb-3/command'
  scalars:
    brightness: 225

# bay up-light
rgb-4: 
  disabled: False
  topic: 'floods/light/rgb-4/command'
  scalars:
    brightness: 225
    hue: -7
    r: 245