tree-in:
  hostname: http://wled-tree-in.knet
  type: string
  disabled: True

  ## rework this from default values
  bri: 255
  segments: 1

  default:
    bri: 255
    seg:
      - n: 'Main'
        start: 0
        stop: 200

porch:
  hostname: http://wled-porch.knet
  type: string

  bri: 255
  segments: 1

  default:
    bri: 255
    seg:
      - n: 'Main'
        start: 0
        stop: 201 # includes extra pixels for garage spoofing

garage:
  hostname: http://wled-garage.knet
  type: string

  bri: 255
  segments: 1

  default:
    bri: 255
    seg:
      - n: 'Main'
        start: 0
        stop: 201 # incluedes extra pixels for porch spoofing

tree-out:
  hostname: http://wled-tree-out.knet
  type: string

  bri: 200
  segments: 1

  default:
    bri: 200
    seg:
      - n: 'Main'
        start: 0
        stop: 125

puck:
  hostname: http://wled-puck.knet
  segments: 1
  type: strip
  disabled: True

  default:
    seg:
      - n: 'Main'
        start: 0
        stop: 36 ## <- verify this

trees-small:
  hostname: http://wled-secondary-trees.knet
  type: string
  disabled: True

  bri: 255
  segments: 2

  default:
    bri: 255
    seg:
      - n: 'Tree1'
        start: 0
        stop: 62
      - n: 'Tree2'
        start: 62
        stop: 124

pumpkins:
  hostname: http://wled-aux2-5v.knet
  type: string
  disabled: False

  bri: 255
  segments: 3

  default:
    bri: 255
    seg:
      - n: 'Pumpkin1'
        start: 0
        stop: 16
      - n: 'Pumpkin2'
        start: 17
        end: 32
      - n: 'Pumpkin3'
        start: 33
        end: 48

angel:
  hostname: http://wled-tree-angel.knet
  type: string
  disabled: True

  bri: 200
  segments: 1

  default:
    bri: 200
    ledmap: 0
    seg:
      - n: 'Main'
        start: 0
        stop: 16
        frz: False
        on: True